name: Build the ROS Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: clean-environment
      run: |
        echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
      
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: my_package
        target-ros1-distro: melodic
        skip-tests: true
