name: Build the ROS Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:     
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic
